import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ErrorBoundary from "../components/ErrorBoundary"; // Error boundary to catch unhandled exceptions in the React tree

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Note: If user data is used in metadata (e.g., dynamic title or description),
  // sanitize it using DOMPurify to prevent XSS. Example:
  // DOMPurify.sanitize(userProvidedTitle || "Default Title")
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col lg:flex-row`}>
        {/* Sidebar Navigation */}
        <nav className="w-full lg:w-64 bg-gray-800 text-white p-4 min-h-screen lg:min-h-screen flex-shrink-0" role="navigation" aria-label="Main navigation">
          <header className="mb-6">
            <h1 className="text-2xl font-bold">FixMyDocs</h1>
          </header>
          <ul className="space-y-2" role="menubar">
            <li role="none">
              <a href="/dashboard" className="block hover:text-blue-300 focus:text-blue-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-gray-800 px-3 py-2 rounded" role="menuitem">
                Dashboard
              </a>
            </li>
            <li role="none">
              <a href="/repos" className="block hover:text-blue-300 focus:text-blue-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-gray-800 px-3 py-2 rounded" role="menuitem">
                Repositories
              </a>
            </li>
            <li role="none">
              <a href="/jobs" className="block hover:text-blue-300 focus:text-blue-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-gray-800 px-3 py-2 rounded" role="menuitem">
                Jobs
              </a>
            </li>
          </ul>
        </nav>
        {/* Main content area wrapped with ErrorBoundary to catch unhandled exceptions */}
        <main className="flex-1">
          <ErrorBoundary>
            {children}
          </ErrorBoundary>
        </main>
      </body>
    </html>
  );
}
