services:
  frontend:
    build:
      context: .
      dockerfile: infra/frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes: # Mount the frontend code for development
      - ./frontend:/app/frontend
      - /app/frontend/node_modules # Anonymous volume to prevent host node_modules from overwriting container's
    env_file:
      - ./frontend/.env
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: infra/backend.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes: # Mount the backend code for development
      - ./backend:/app/backend
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: infra/worker.Dockerfile
    env_file:
      - ./worker/.env
    depends_on:
      - db
      - redis
    volumes: # Mount the worker code for development
      - ./worker:/app/worker
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge